name: Deploy Laravel Sertifikasi InvestaLearning to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2 # SESUAIKAN VPS

      - name: 📦 Install Composer
        run: composer install --no-progress --prefer-dist --no-dev

      - name: 🚀 Deploy ke VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd ${{ secrets.SERVER_PATH }}

            echo "Pull code"
            git pull origin main

            echo "Install composer"
            composer install --no-dev --optimize-autoloader

            echo "Load NVM"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22

            echo "Node version:"
            node -v

            echo "Install node modules"
            npm install

            echo "Build frontend"
            npm run build

            echo "Migrate"
            php artisan migrate --force

            echo "Clear cache"
            php artisan optimize:clear

            echo "Cache ulang"
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Permission"
            chmod -R 777 storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache

            echo "Reload PHP & Nginx"
            sudo systemctl reload php8.2-fpm # SESUAIKAN
            sudo systemctl reload nginx
